version: '2'

services:
  filebeat:
    build:
      context: ./filebeat
      args:
        ELASTIC_VERSION: $DOCKER_FILEBEAT_ELASTIC_VERSION
    container_name: filebeat
    restart: always
    volumes:
      - ./data/filebeat:/usr/share/filebeat/data
      - ./logs/filebeat:/usr/share/filebeat/logs
    networks:
      - dockerelk_elk

networks:
  dockerelk_elk:
    external: true